/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectionProvider.ConnectionProviderCode;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author aman
 */
public class InsertResult extends javax.swing.JFrame {

    /**
     * Creates new form InsertResult
     */
    public InsertResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rollNo_label = new javax.swing.JLabel();
        rollNo_field = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        physicsMarks_field = new javax.swing.JTextField();
        mathsMarks_field = new javax.swing.JTextField();
        chemistryMarks_field = new javax.swing.JTextField();
        electricalMarks_field = new javax.swing.JTextField();
        biologyMarks_field = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rollNo_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rollNo_label.setText("Roll no");
        getContentPane().add(rollNo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 34, -1, -1));
        getContentPane().add(rollNo_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 31, 115, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 31, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Roll No", "Gender", "Father's Name", "Course", "Branch"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 520, 54));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Physics Marks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Maths Marks");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Chemistry Marks");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Electrical Marks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Biology Marks");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));
        getContentPane().add(physicsMarks_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 138, 100, -1));
        getContentPane().add(mathsMarks_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, -1));
        getContentPane().add(chemistryMarks_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 100, -1));
        getContentPane().add(electricalMarks_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 100, -1));
        getContentPane().add(biologyMarks_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 100, -1));

        submit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-submit-document-32.png"))); // NOI18N
        submit_button.setText("Save");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-cancel-24.png"))); // NOI18N
        exit_button.setText("Exit");
        exit_button.setMaximumSize(new java.awt.Dimension(90, 39));
        exit_button.setMinimumSize(new java.awt.Dimension(90, 39));
        exit_button.setPreferredSize(new java.awt.Dimension(90, 39));
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(550, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(550, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(550, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        String rollNo=rollNo_field.getText();
        int physicsMarks=Integer.parseInt(physicsMarks_field.getText());
        int mathsMarks=Integer.parseInt(mathsMarks_field.getText());
        int chemMarks=Integer.parseInt(chemistryMarks_field.getText());
        int electricalMarks=Integer.parseInt(electricalMarks_field.getText());
        int bioMarks=Integer.parseInt(biologyMarks_field.getText());
        int total=physicsMarks+mathsMarks+chemMarks+electricalMarks+bioMarks;
        
        try{
            Connection con=ConnectionProviderCode.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into result values('"+rollNo+"','"+physicsMarks+"','"+mathsMarks+"','"+chemMarks+"','"+electricalMarks+"','"+bioMarks+"','"+total+"')");
            JOptionPane.showMessageDialog(null, "Added Successfully");
            setVisible(false);
            InsertResult frame=new InsertResult();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        int response=JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Submit", JOptionPane.YES_NO_OPTION);
        if(response==0)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String rollNo=rollNo_field.getText();
        try{
            Connection con=ConnectionProviderCode.getCon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE); 
            ResultSet rs=st.executeQuery("SELECT * FROM student where rollNo='"+rollNo+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first()){
                JOptionPane.showMessageDialog(null, "Entered Roll No dosent exists.");
            }else{
            rollNo_field.setEditable(false);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biologyMarks_field;
    private javax.swing.JTextField chemistryMarks_field;
    private javax.swing.JTextField electricalMarks_field;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mathsMarks_field;
    private javax.swing.JTextField physicsMarks_field;
    private javax.swing.JTextField rollNo_field;
    private javax.swing.JLabel rollNo_label;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
